# Generated by Django 5.1.4 on 2024-12-29 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkEasyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('host', 'Host'), ('both', 'Both')], default='driver', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.BooleanField(default=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='ParkEasyApp.parkeasyuser')),
            ],
        ),
        migrations.CreateModel(
            name='GracePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkingspace')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('time_extension', models.DurationField(blank=True, null=True)),
                ('grace_period', models.DurationField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ParkEasyApp.parkeasyuser')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkingspace')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.1, '0.1'), (0.2, '0.2'), (0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0'), (1.1, '1.1'), (1.2, '1.2'), (1.3, '1.3'), (1.4, '1.4'), (1.5, '1.5'), (1.6, '1.6'), (1.7, '1.7'), (1.8, '1.8'), (1.9, '1.9'), (2.0, '2.0'), (2.1, '2.1'), (2.2, '2.2'), (2.3, '2.3'), (2.4, '2.4'), (2.5, '2.5'), (2.6, '2.6'), (2.7, '2.7'), (2.8, '2.8'), (2.9, '2.9'), (3.0, '3.0'), (3.1, '3.1'), (3.2, '3.2'), (3.3, '3.3'), (3.4, '3.4'), (3.5, '3.5'), (3.6, '3.6'), (3.7, '3.7'), (3.8, '3.8'), (3.9, '3.9'), (4.0, '4.0'), (4.1, '4.1'), (4.2, '4.2'), (4.3, '4.3'), (4.4, '4.4'), (4.5, '4.5'), (4.6, '4.6'), (4.7, '4.7'), (4.8, '4.8'), (4.9, '4.9'), (5.0, '5.0')], decimal_places=2, max_digits=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkeasyuser')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkingspace')),
            ],
        ),
        migrations.CreateModel(
            name='TimeExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_extension', models.DurationField()),
                ('approved', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('reminder', 'Reminder')], max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkeasyuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ParkEasyApp_user_id_b15af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkeasyuser')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'date_earned'], name='ParkEasyApp_host_id_07dfae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['host', 'location'], name='ParkEasyApp_host_id_957e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='graceperiod',
            index=models.Index(fields=['parking_space'], name='ParkEasyApp_parking_93b840_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver', 'parking_space', 'status'], name='ParkEasyApp_driver__f8daa6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'payment_status'], name='ParkEasyApp_booking_e0fda3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['driver', 'parking_space'], name='ParkEasyApp_driver__32f358_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('driver', 'parking_space')},
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['booking', 'approved'], name='ParkEasyApp_booking_95bf21_idx'),
        ),
    ]
