# Generated by Django 5.1.4 on 2025-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
