# Generated by Django 5.1.4 on 2025-01-05 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0002_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='ParkEasyApp_driver__f8daa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='ParkEasyApp_driver__32f358_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='driver',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='driver',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'parking_space')},
        ),
        migrations.RemoveField(
            model_name='parkeasyuser',
            name='role',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('parking_space', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'parking_space', 'status'], name='ParkEasyApp_user_id_f9e1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'parking_space'], name='ParkEasyApp_user_id_1a97b1_idx'),
        ),
    ]
