# Generated by Django 5.1.4 on 2025-01-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0004_alter_booking_end_date_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
