# Generated by Django 5.1.4 on 2025-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0005_parkingspace_latitude_parkingspace_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkeasyuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
