# Generated by Django 5.1.4 on 2025-01-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0006_parkeasyuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
