# Generated by Django 5.1.4 on 2025-01-19 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0008_alter_parkingspace_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='ParkEasyApp_user_id_1a97b1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='name',
            field=models.CharField(default='Default Parking Space', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], default='card', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkingspace'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParkEasyApp.parkeasyuser'),
        ),
    ]
