# Generated by Django 5.1.4 on 2025-01-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0009_remove_review_parkeasyapp_user_id_1a97b1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ParkingSpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_space_images/')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ParkEasyApp.parkingspace')),
            ],
        ),
    ]
