# Generated by Django 5.1.4 on 2025-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0010_alter_parkingspace_name_parkingspaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_spaces/'),
        ),
        migrations.DeleteModel(
            name='ParkingSpaceImage',
        ),
    ]
