# Generated by Django 5.1.4 on 2025-01-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0011_parkingspace_image_delete_parkingspaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkeasyuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_spaces'),
        ),
    ]
