# Generated by Django 5.1.4 on 2025-01-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0012_parkeasyuser_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='ParkEasyApp_user_id_b15af5_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='parkeasyuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='image',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRM', 'Booking Confirmation'), ('PAYMENT_CONFIRM', 'Payment Confirmation'), ('PENDING_APPROVAL', 'Pending Approval'), ('PARKING_AVAILABLE', 'Parking Available'), ('EXTENSION_REQUEST', 'Time Extension Request'), ('GRACE_PERIOD', 'Grace Period Expiry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
