# Generated by Django 5.1.4 on 2025-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0013_remove_notification_parkeasyapp_user_id_b15af5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_images/'),
        ),
    ]
