# Generated by Django 5.1.4 on 2025-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0014_parkingspace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRM', 'Booking Confirmation'), ('PAYMENT_CONFIRM', 'Payment Confirmation'), ('PENDING_APPROVAL', 'Pending Approval'), ('PARKING_AVAILABLE', 'Parking Available'), ('EXTENSION_REQUEST', 'Time Extension Request'), ('GRACE_PERIOD', 'Grace Period Expiry'), ('USER_REGISTRATION', 'New User Registration'), ('ADMIN_PAYMENT', 'Admin Payment Notification'), ('NEW_PARKING_SPACE', 'New Parking Space Created')], max_length=50),
        ),
    ]
