# Generated by Django 5.1.4 on 2025-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0015_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRM', 'Booking Confirmation'), ('PAYMENT_CONFIRM', 'Payment Confirmation'), ('PENDING_APPROVAL', 'Pending Approval'), ('PARKING_AVAILABLE', 'Parking Available'), ('EXTENSION_REQUEST', 'Time Extension Request'), ('GRACE_PERIOD', 'Grace Period Expiry'), ('USER_REGISTRATION', 'New User Registration'), ('ADMIN_PAYMENT', 'Admin Payment Notification'), ('NEW_PARKING_SPACE', 'New Parking Space Created'), ('USER_DELETION', 'User Deletion'), ('PARKING_DELETED', 'Parking Space Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
