# Generated by Django 5.1.4 on 2025-01-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasyApp', '0016_payment_admin_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_earnings', to='ParkEasyApp.parkeasyuser'),
        ),
    ]
